apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yk7wsyt3z-go 
  janus-idp.io/tekton: yk7wsyt3z-go
  backstage.io/kubernetes-id: yk7wsyt3z-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yk7wsyt3z-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml